// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20251125091457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Docks", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualifications", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("SetupTime")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Resources", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.ShippingAgents.ShippingAgentOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LegalName");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaxNumber");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgentOrganizations", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.ShippingAgents.ShippingAgentRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ShippingAgentOrganizationId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentOrganizationId");

                    b.ToTable("ShippingAgentRepresentatives", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MecanographicNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MecanographicNumber");

                    b.Property<string>("OperationalWindow")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MecanographicNumber")
                        .IsUnique();

                    b.ToTable("StaffMembers", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.StorageAreas.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("numeric");

                    b.Property<string>("DockDistances")
                        .HasColumnType("jsonb");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Users.PendingUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IamUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IamUserId")
                        .IsUnique();

                    b.ToTable("PendingUsers", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivationToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IamUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivationToken");

                    b.HasIndex("IamUserId")
                        .IsUnique();

                    b.ToTable("Users", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.VesselTypes.VesselType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.VesselVisitNotifications.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDockId")
                        .HasColumnType("uuid")
                        .HasColumnName("AssignedDockId");

                    b.Property<Guid?>("DecidingOfficerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DecisionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ETA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ETD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDockId");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VesselTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", "ddd");
                });

            modelBuilder.Entity("DockAllowedVesselTypes", b =>
                {
                    b.Property<Guid>("DockId")
                        .HasColumnType("text");

                    b.Property<Guid>("VesselTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("DockId", "VesselTypeId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("DockAllowedVesselTypes", "ddd");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<string>("QualificationsId")
                        .HasColumnType("text");

                    b.Property<string>("StaffMemberId")
                        .HasColumnType("text");

                    b.HasKey("QualificationsId", "StaffMemberId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("QualificationStaffMember", "ddd");
                });

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Docks.Depth", "Depth", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("text");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Depth");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Docks.DockLocation", "DockLocation", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DockLocation");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Docks.DockName", "DockName", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DockName");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Docks.Length", "Length", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("text");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Length");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Docks.MaxDraft", "MaxDraft", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("text");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("MaxDraft");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("Depth");

                    b.Navigation("DockLocation");

                    b.Navigation("DockName");

                    b.Navigation("Length");

                    b.Navigation("MaxDraft");
                });

            modelBuilder.Entity("DDDSample1.Domain.Resources.Resource", b =>
                {
                    b.OwnsMany("DDDSample1.Domain.Qualifications.QualificationId", "RequiredQualifications", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("QualificationId");

                            b1.HasKey("ResourceId", "Id");

                            b1.ToTable("QualificationId", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("RequiredQualifications");
                });

            modelBuilder.Entity("DDDSample1.Domain.ShippingAgents.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("DDDSample1.Domain.ShippingAgents.ShippingAgentOrganization", null)
                        .WithMany("Representatives")
                        .HasForeignKey("ShippingAgentOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("DDDSample1.Domain.ShippingAgents.CitizenId", "CitizenId", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CitizenId");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("DDDSample1.Domain.ShippingAgents.Nationality", "Nationality", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Nationality");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("DDDSample1.Domain.ShippingAgents.RepEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("DDDSample1.Domain.ShippingAgents.RepName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("DDDSample1.Domain.ShippingAgents.RepPhone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Phone");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.Navigation("CitizenId");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Nationality");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("DDDSample1.Domain.Users.PendingUser", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Users.UserEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("PendingUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("PendingUserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PendingUsers", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("PendingUserId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Users.UserName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PendingUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("PendingUserId");

                            b1.ToTable("PendingUsers", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("PendingUserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("DDDSample1.Domain.Users.User", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Users.UserEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Users.UserName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Users.UserRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Role");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Users.UserStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Status");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DDDSample1.Domain.VesselTypes.VesselType", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.VesselTypes.OperationalConstraints", "Constraints", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxBays")
                                .HasColumnType("integer")
                                .HasColumnName("MaxBays");

                            b1.Property<int>("MaxRows")
                                .HasColumnType("integer")
                                .HasColumnName("MaxRows");

                            b1.Property<int>("MaxTiers")
                                .HasColumnType("integer")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("DDDSample1.Domain.VesselVisitNotifications.VesselVisitNotification", b =>
                {
                    b.HasOne("DDDSample1.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("AssignedDockId");

                    b.HasOne("DDDSample1.Domain.ShippingAgents.ShippingAgentRepresentative", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById");

                    b.HasOne("DDDSample1.Domain.Vessels.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId");

                    b.OwnsMany("DDDSample1.Domain.VesselVisitNotifications.CargoManifest", "CargoManifests", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ManifestType")
                                .HasColumnType("text");

                            b1.HasKey("VesselVisitNotificationId", "Id");

                            b1.ToTable("CargoManifest", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");

                            b1.OwnsMany("DDDSample1.Domain.VesselVisitNotifications.ContainerIdentifier", "Containers", b2 =>
                                {
                                    b2.Property<Guid>("CargoManifestVesselVisitNotificationId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CargoManifestId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Value")
                                        .HasColumnType("text")
                                        .HasColumnName("ContainerIdentifier");

                                    b2.HasKey("CargoManifestVesselVisitNotificationId", "CargoManifestId", "Id");

                                    b2.ToTable("ContainerIdentifier", "ddd");

                                    b2.WithOwner()
                                        .HasForeignKey("CargoManifestVesselVisitNotificationId", "CargoManifestId");
                                });

                            b1.Navigation("Containers");
                        });

                    b.OwnsMany("DDDSample1.Domain.VesselVisitNotifications.CrewMember", "CrewMembers", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CitizenId")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .HasColumnType("text");

                            b1.HasKey("VesselVisitNotificationId", "Id");

                            b1.ToTable("CrewMember", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("DDDSample1.Domain.VesselVisitNotifications.VisitStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Status");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.Navigation("CargoManifests");

                    b.Navigation("CrewMembers");

                    b.Navigation("Status");

                    b.Navigation("SubmittedBy");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("DDDSample1.Domain.ShippingAgents.ShippingAgentOrganization", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.VesselTypes.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DDDSample1.Domain.Vessels.IMO", "IMO", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("IMO");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Vessels.VesselName", "VesselName", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VesselName");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "ddd");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("IMO");

                    b.Navigation("Owner");

                    b.Navigation("VesselName");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("DockAllowedVesselTypes", b =>
                {
                    b.HasOne("DDDSample1.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.VesselTypes.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("DDDSample1.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.StaffMembers.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDSample1.Domain.ShippingAgents.ShippingAgentOrganization", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
