@startuml
skinparam monochrome true
skinparam shadowing false

title Sequence Diagram - Level 2 (Components) for US06

actor "Port Authority Officer" as PAO
participant "Controller" as CTRL
participant "Service" as SVC
participant "Repository" as REPO

PAO -> CTRL : POST request
CTRL -> SVC : RegisterOrganization
SVC -> REPO : Add organization
REPO --> SVC : Success
SVC --> CTRL : DTO
CTRL --> PAO : Response
@enduml