@startuml
skinparam linetype ortho
!define NODE node
!define COMPONENT component
!define DATABASE database
!include <C4/C4_Container>

skinparam monochrome true

NODE "localhost:5173" {
        COMPONENT "Browser" {
            COMPONENT "Single Page Application"
            COMPONENT "3D Visualization Service"
        }
}

NODE "localhost:5000" {
        COMPONENT "BackendAPI Module"
}

NODE "localhost:5161" {
        COMPONENT "OEM Module"
}
NODE "localhost:5107" {
        COMPONENT "Scheduling Module"
}

NODE "vs216.dei.isep.ipp.pt" {
        DATABASE "SQL Database"
        DATABASE "MongoDB Database"
}

NODE "Auth0" {
}

"localhost:5173" --> "localhost:5000"
"localhost:5173" --> "localhost:5161"
"localhost:5173" --> "localhost:5107"
"localhost:5161" -> "localhost:5107"
"localhost:5173" --> "Auth0"
"localhost:5000" -down-> "vs216.dei.isep.ipp.pt"
"localhost:5161" -down-> "vs216.dei.isep.ipp.pt"

@enduml