name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore master.sln

      - name: Build
        run: dotnet build master.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test master.sln --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults  || true
        continue-on-error: true

      - name: Publish Backend API
        run: dotnet publish BackendAPI/Backend.csproj --no-build --configuration Release --output ./publish/BackendAPI

      - name: Remove duplicate appsettings files
        run: rm -f /src/BackendAPI/appsettings.json && \ rm -f /src/BackendAPI/appsettings.*.json

      - name: Publish Scheduling API
        run: dotnet publish Scheduling/SchedulingAPI/SchedulingAPI.csproj --no-build --configuration Release --output ./publish/SchedulingAPI
  

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./TestResults/
